# Ao ocorrer excessões (erros), normalmente o programa irá encerrar
# use [Try - Except] para uma rota alternativa em casa de erro

try:
  print(x) # x no defined ~ error
except:
  print("An exception occurred")
